// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtYm3OGk-pjEGplnopsNeYxp4tmWQIYw',
    appId: '1:507101633813:web:ddecb97a152573ac735d1c',
    messagingSenderId: '507101633813',
    projectId: 'hara-hijab',
    authDomain: 'hara-hijab.firebaseapp.com',
    storageBucket: 'hara-hijab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxr40hj3sXUCnJA_2nXgmTjqGv-bQh_Q',
    appId: '1:507101633813:android:63b2c5310f852854735d1c',
    messagingSenderId: '507101633813',
    projectId: 'hara-hijab',
    storageBucket: 'hara-hijab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChg6xLCBAztbsC4JKTrBU4xP1SRFn7eaU',
    appId: '1:507101633813:ios:59a07b8de8159ae9735d1c',
    messagingSenderId: '507101633813',
    projectId: 'hara-hijab',
    storageBucket: 'hara-hijab.firebasestorage.app',
    androidClientId: '507101633813-9qi9bveig9tti7lgkrvkqarav00gvcjg.apps.googleusercontent.com',
    iosClientId: '507101633813-37u6reff7807nbiqaaa2gpofgvbtod0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.appHara',
  );
}
